apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-nodeport
spec:
  type: NodePort
  selector:
    app: simple-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007